# Generated by Django 3.2.8 on 2021-12-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anteriortoken', models.CharField(blank=True, max_length=500, null=True)),
                ('actualtoken', models.CharField(blank=True, max_length=500, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tokenLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('tokena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
